name: interstellar

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.0.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.4
  http: ^1.2.2
  http_parser: ^4.1.1
  path: ^1.9.0
  mime: ^2.0.0
  infinite_scroll_pagination: ^4.1.0
  intl: any
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5
  media_kit_libs_video: ^1.0.5
  oauth2: ^2.0.3
  provider: ^6.1.2
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  youtube_explode_dart: ^2.3.6
  freezed_annotation: ^2.4.4
  badges: ^3.1.2
  image_picker: ^1.1.2
  dynamic_color: ^1.7.0
  markdown: ^7.2.2
  expandable: ^5.0.1
  blurhash_ffi: ^1.2.6
  unifiedpush: ^5.0.2
  webpush_encryption: 1.0.0-rc1
  flutter_local_notifications: ^18.0.1
  flex_color_scheme: ^7.3.1
  share_plus: ^10.1.3
  path_provider: ^2.1.5
  window_manager: ^0.4.3
  material_symbols_icons: ^4.2801.0
  json_annotation: ^4.9.0
  sembast: ^3.8.0
  package_info_plus: ^8.1.2
  flutter_localized_locales: ^2.0.5

dev_dependencies:
  flutter_lints: ^3.0.2

  flutter_launcher_icons: # This is until the next release > ^0.13.1
    git:
      url: 'https://github.com/fluttercommunity/flutter_launcher_icons.git'
      ref: '006cb1ed53f969bf11816cde5b16dd520e1ee40e'
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the icons directory to the application.
    - assets/icons/

flutter_launcher_icons:
  image_path: 'assets/icons/logo.png'
  android: true
  adaptive_icon_foreground: 'assets/icons/logo-android-foreground.png'
  adaptive_icon_background: '#294062'
  adaptive_icon_monochrome: 'assets/icons/logo-android-monochrome.png'
  windows:
    generate: true
